### ISSUE TITLE
[BUG] bizdays missing a business day in count

### ISSUE THREAD

**Issue by penniedfe** [wilsonfreitas/R-bizdays#108]
I have created a calendar using UK holidays as the basis and only Thursdays and Fridays as business days: 

```
bizdays::load_quantlib_calendars("UnitedKingdom", from = as.Date("2024-01-01"), to = as.Date("2024-12-31"), financial = FALSE)
uk_holidays <- bizdays::holidays("QuantLib/UnitedKingdom")

my_cal <- bizdays::create.calendar('nursery_calendar', holidays = uk_holidays, weekdays = c('monday', 'tuesday', 'wednesday', 'saturday', 'sunday'), start.date = as.Date("2024-01-01"), end.date = as.Date("2024-12-31"), financial = FALSE)

```

bizdays seems to work for all weeks of 2024, apart from the final working week, which returns 0 when it should return 1 as the 27th would be a working day. is.bizday returns a TRUE for the 27th so I'm not quite clear what is going on here:

```
bizdays::bizdays(from = as.Date("2024-12-23"), to = as.Date("2024-12-29"), cal = my_cal)

bizdays::is.bizday(as.Date("2024-12-27"), cal = my_cal)
```

**Comment by wilsonfreitas** [comment]
Yes, there is a BUG in the reverse index.
Thanks for reporting this specific issue.
The correction will come with the next release.
