### ISSUE TITLE
New Calendar Chinese New Year

### ISSUE THREAD

**Issue by doncqueurs** [wilsonfreitas/R-bizdays#11]
Hi,

On your site you noted that were interested in adding more list of holiday to future releases of your R package. I have compiled a list of the Chinese New Year days. Of course, this are not strictly holiday as different Asian countries are dealing differently with it. Below a list of the days since between 1996 and 2013:

19-Feb-96
07-Feb-97
28-Jan-98
16-Feb-99
05-Feb-00
24-Jan-01
12-Feb-02
01-Feb-03
22-Jan-04
09-Feb-05
29-Jan-06
18-Feb-07
07-Feb-08
26-Jan-09
14-Feb-10
03-Feb-11
23-Jan-12
10-Feb-13
31-Jan-14
19-Feb-15
08-Feb-16
28-Jan-17
16-Feb-18
05-Feb-19
25-Jan-20
12-Feb-21
01-Feb-22
22-Jan-23
10-Feb-24
29-Jan-25
17-Feb-26
06-Feb-27
26-Jan-28
13-Feb-29
03-Feb-30
23-Jan-31

**Comment by wilsonfreitas** [comment]
Use dates from http://www.chinesenewyears.info/chinese-new-year-calendar.php instead

**Comment by stchau4work** [comment]
I've implemented the CNY holidays algorithm for 200 years https://github.com/stchau4work/chineseCalendar
