### ISSUE TITLE
start.date and end.date in Calendar

### ISSUE THREAD

**Issue by stefanfritsch** [wilsonfreitas/R-bizdays#26]
Hi,

Calendar overrides start.date and end.date with the holidays list:

`The arguments start.date and end.date can be set but once holidays is set, start.date is
defined to min(holidays) and end.date to max(holidays).`

I can't think of a single reason why this is a good idea. Is there a technical issue for this?

Thx
Stefan

**Comment by wilsonfreitas** [comment]
That simply worked for me, but now I think it is better.
Done!
