### ISSUE TITLE
Incorrect calculation

### ISSUE THREAD

**Issue by stefanfritsch** [wilsonfreitas/R-bizdays#27]
Hi,

the following results in `[1] 4 4 4` on my machine with the current CRAN version of bizdays.

As I see it the result should be 4, 3, 3

It's three Monday-Friday periods. One has a holiday on Monday, another on Thursday.

```R
Cal<-Calendar(ymd(c("1970-01-01", "2015-05-14", "2015-05-25", "2037-12-31")),
              weekdays=c("saturday","sunday"))

x<-ymd("2015-04-13 UTC", "2015-05-11 UTC", "2015-05-25 UTC")
y<-ymd("2015-04-17 UTC", "2015-05-15 UTC", "2015-05-29 UTC")

bizdays(x,y,Cal)
```

I'm happy to acknowledge that I might be just too stupid to see the problem but it looks like a bug to me :)

Ciao,
Stefan

**Comment by wilsonfreitas** [comment]
Try this.

```
> cal <- Calendar(as.Date(c("1970-01-01", "2015-05-14", "2015-05-25", "2037-12-31")),
+ weekdays=c("saturday","sunday"))
> x <- ymd("2015-04-13 UTC", "2015-05-11 UTC", "2015-05-25 UTC")
> y <- ymd("2015-04-17 UTC", "2015-05-15 UTC", "2015-05-29 UTC")
> bizdays(x,y,Cal)
[1] 4 3 3
```

Indeed it is a bug and I'll fix it.
Tks,
Wilson

**Comment by wilsonfreitas** [comment]
Calendar now accepts POSIX* objects in holidays argument.
Done!
