### ISSUE TITLE
US financial holidays?

### ISSUE THREAD

**Issue by ashutosh-gupta** [wilsonfreitas/R-bizdays#29]
Hi There,
Thanks for the useful package.
 
I have been using `holidaysANBIMA` as the calendar and my calculations were not matching up.
Just realized that Feb 8-9, 2016 is set as holiday in ANBIMA, but it's not even an optional holiday in US. 
Any ideas which calendars are appropriate for USA?
 
If you don't have a database, I'll be happy to share one. 
 
Thanks,
A.

**Comment by wilsonfreitas** [comment]
`holidaysANBIMA` has the holidays used in Brazil in derivatives and OTC markets.
Each market has its own set of holidays, for US I'd suggest:

- [NYSE](https://www.nyse.com/markets/hours-calendars)
- [NASDAQ](http://www.nasdaqtrader.com/Trader.aspx?id=Calendar)
- [SIFMA](http://www.sifma.org/services/holiday-schedule/)
- [CME](http://www.cmegroup.com/tools-information/holiday-calendar/)

for now you have to pick a calendar and build its holidays list, but I'm planning to provide these calendars with bizdays soon.

Thanks in advance,

Wilson
