### ISSUE TITLE
Problems after upgrading to latest version

### ISSUE THREAD

**Issue by eonsmile** [wilsonfreitas/R-bizdays#49]
After upgrading to the newest bizdays (I last installed a year ago), the following code wouldn't work (whereas it worked using the previous version), please help!

library(bizdays)
y=2012
m=2
cal.US=create.calendar('cal.US',weekdays=c('saturday','sunday'))
tmp=as.Date(paste(y,m,26,sep="-"))
z=offset(tmp,-7,'cal.US')
print(z)

---

> print(z)
[1] NA

**Comment by wilsonfreitas** [comment]
The problem is the date you use (2012-02-26) is a non-working day, it is a sunday.
You should adjust the date before passing to the offset function.
In the earlier versions this argument was adjusted with adjust.previous, but I decided that this decision must be a user's decision.
So now if you provide a non-business day to offset it returns NA. 

Take a look at the examples below and see what's the best for you.

```r
> offset(adjust.previous('2012-02-26', 'weekends'), -7, 'weekends')
[1] "2012-02-15"
> offset(adjust.next('2012-02-26', 'weekends'), -7, 'weekends')
[1] "2012-02-16"
```
I don't like that approach but I couldn't figure out what to do.

tks

**Comment by eonsmile** [comment]
thanks; solves for question.  I wrote my own little wrapper to work around this:

#############################################################################
# Offset that works even if entered date lands on a holiday (updated 11Feb17)
#############################################################################
offset2<-function(dates,n,cal='cal.US'){
  if(n==0){
    return(dates)
  }else if(n>0){
    return(offset(adjust.previous(dates,cal),n,cal))
  }else if(n<0){
    return(offset(adjust.next(dates,cal),n,cal))
  }
}

**Comment by wilsonfreitas** [comment]
Hi @eonsmile 

I have changed `offset` (commit ab84ecf05010f9ed26f5ec58329db2b5f5bd22ba) and now it handles non business days and `n = 0`.
Please check it out.

**Comment by eonsmile** [comment]
Thanks, can you let us know what the logic is now? 


-------- Original message --------From: Wilson Freitas <notifications@github.com> Date: 4/11/17  5:24 PM  (GMT+09:00) To: wilsonfreitas/R-bizdays <R-bizdays@noreply.github.com> Cc: eonsmile <simonlee@me.com>, Mention <mention@noreply.github.com> Subject: Re: [wilsonfreitas/R-bizdays] Problems after upgrading to latest
  version (#49) 
Hi @eonsmile
I have changed offset (commit ab84ecf) and now it handles non business days and n = 0.

Please check it out.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wilsonfreitas/R-bizdays","title":"wilsonfreitas/R-bizdays","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wilsonfreitas/R-bizdays"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wilsonfreitas in #49: Hi @eonsmile \r\n\r\nI have changed `offset` (commit ab84ecf05010f9ed26f5ec58329db2b5f5bd22ba) and now it handles non business days and `n = 0`.\r\nPlease check it out.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/wilsonfreitas/R-bizdays/issues/49#issuecomment-293186944"}}}

**Comment by wilsonfreitas** [comment]
I plan to explain the logic in a future vignette. But, for now if you run the example above you'll get:

```
> bizdays::offset("2012-02-26", c(-7, 0, 7), "weekends")
# [1] "2012-02-16" "2012-02-26" "2012-03-06"
```

which makes more sense to me now.

**Comment by eonsmile** [comment]
I installed version 1.0.2 already, but still get the following:

 

> bizdays::offset("2012-02-26", c(-7, 0, 7), "weekends")

[1] NA NA NA

**Comment by eonsmile** [comment]
Sorry, just a session problem; I can verify the fix is in already, thanks.

 

From: Simon Lee [mailto:simonlee@me.com] 
Sent: Thursday, April 13, 2017 7:37 PM
To: 'wilsonfreitas/R-bizdays' <reply@reply.github.com>; 'wilsonfreitas/R-bizdays' <R-bizdays@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [wilsonfreitas/R-bizdays] Problems after upgrading to latest version (#49)

 

I installed version 1.0.2 already, but still get the following:

 

> bizdays::offset("2012-02-26", c(-7, 0, 7), "weekends")

[1] NA NA NA
