### ISSUE TITLE
NYSE Calendar

### ISSUE THREAD

**Issue by DerekYves** [wilsonfreitas/R-bizdays#58]
Thanks for this awesome package. I'm presently compiling quantlib and will see if the method you provide for it's calendars will work. In the meantime, if I just want to bring in the NYSE trading calendar, do you see anything wrong with the following? It works, but I'm cognizant that the returned object is a dateTime class:

```
library(lubridate)
library(bizdays)
nyse <- timeDate::holidayNYSE(2000:year(Sys.Date()) +1)
create.calendar(name='NYSE', holidays=nyse, weekdays=c('saturday', 'sunday'))
bizdays.options$set(default.calendar='NYSE')
```

If this does work perhaps this could be added as an example in the documentation for Create calendar?

**Comment by wilsonfreitas** [comment]
Hi @DerekYves 

All bizdays functions which return dates return Date objects.
This code isn't wrong but since timeDate is part of Rmetrics you can use its integration.

```r
load_rmetrics_calendars(2000:year(Sys.Date()) +1)
# Calendar Rmetrics/LONDON loaded
# Calendar Rmetrics/NERC loaded
# Calendar Rmetrics/NYSE loaded
# Calendar Rmetrics/TSX loaded
# Calendar Rmetrics/ZURICH loaded
calendars()
# Calendars: 
# actual, Brazil/ANBIMA, Rmetrics/LONDON, Rmetrics/NERC, Rmetrics/NYSE, Rmetrics/TSX, Rmetrics/ZURICH, weekends
bizdays.options$set(default.calendar = "Rmetrics/NYSE")
bizdays.options$get('default.calendar')
# [1] "Rmetrics/NYSE"
```

You see, I believe it's safe and simple.
