### ISSUE TITLE
Add financial argument to create.bizdays

### ISSUE THREAD

**Issue by KZRKZR** [wilsonfreitas/R-bizdays#62]
I find strange behavior of bizdays function:
`hd<- as.Date(    c(
  
  "2017-01-02",  # New Year's Day
  "2017-01-16",  # Birthday of Martin Luther King, Jr.
  "2017-02-20",  # Washington's Birthday
  "2017-05-29",  # Memorial Day
  "2017-07-04",  # Independence Day
  "2017-09-04",  # Labor Day
  "2017-10-09",  # Columbus Day
  "2017-11-10",  # Veterans Day
  "2017-11-23",  # Thanksgiving Day
  "2017-12-25"  # Christmas Day

)
,format = "%Y-%m-%d",tz="CST6CDT")

create.calendar("USA2017", holidays=hd, start.date='2017-01-01',end.date='2017-12-31', weekdays=c("saturday", "sunday"))
bizdays("2017-09-04","2017-09-08","USA2017")
bizdays("2017-09-04","2017-09-09","USA2017")
bizseq("2017-09-04","2017-09-08","USA2017")
bizseq("2017-09-04","2017-09-09","USA2017")`
Result:
> bizdays("2017-09-04","2017-09-08","USA2017")
[1] 3
> bizdays("2017-09-04","2017-09-09","USA2017")
[1] 4
> bizseq("2017-09-04","2017-09-08","USA2017")
[1] "2017-09-05" "2017-09-06" "2017-09-07" "2017-09-08"
> bizseq("2017-09-04","2017-09-09","USA2017")
[1] "2017-09-05" "2017-09-06" "2017-09-07" "2017-09-08"
I expect that bizdays("2017-09-04","2017-09-09","USA2017") must return 3 also.

**Comment by bbrewington** [comment]
I stepped through the function call `bizdays("2017-09-04","2017-09-09","USA2017")` and noticed that the `adjust.from` part of the bizdays function might not be working.

Here's a link to that line of code from commit [8173b2b](https://github.com/wilsonfreitas/R-bizdays/commit/8173b2bd609f03089636e774c0f09b97d71cc7c8):
https://github.com/wilsonfreitas/R-bizdays/blob/000986d3c86f9d7cfda43a28c83960d5f40ca838/R/bizdays.R#L78-L79

**Comment by wilsonfreitas** [comment]
This difference appears because of the way bizdays works computing business days between two dates. This was designed for financial purposes and for four business days you have three days of interest rate compounding.

I believe a new argument must be added to `create.calendar` in order to specify whether or not the calendar is for financial purposes.
Maybe `financial = FALSE`.

I am changing the title of this issue to reflect that.

**Comment by wilsonfreitas** [comment]
@KZRKZR and @bbrewington 

I believe I have finally solved this issue.
I've introduced the argument  `financial` to `create.calendar` that makes it possible to create non financial calendars if `financial = TRUE`.
Non financial calendars are consistent with `bizseq` returned sequences.
Please, see the code below.

```r
> hd<- as.Date( c(
+   "2017-01-02", # New Year's Day
+   "2017-01-16", # Birthday of Martin Luther King, Jr.
+   "2017-02-20", # Washington's Birthday
+   "2017-05-29", # Memorial Day
+   "2017-07-04", # Independence Day
+   "2017-09-04", # Labor Day
+   "2017-10-09", # Columbus Day
+   "2017-11-10", # Veterans Day
+   "2017-11-23", # Thanksgiving Day
+   "2017-12-25" # Christmas Day
+ ), format = "%Y-%m-%d",tz="CST6CDT")
> 
> create.calendar("USA2017", holidays=hd, start.date='2017-01-01',
+                 end.date='2017-12-31', weekdays=c("saturday", "sunday"),
+                 financial = FALSE)
> 
> # both from and to are non bizdays
> c(bizdays("2017-09-04","2017-09-08","USA2017"),
+   bizdays("2017-09-04","2017-09-09","USA2017"))
[1] 4 4
> # from is non bizdays
> c(bizdays("2017-09-04","2017-09-08","USA2017"),
+   bizdays("2017-09-05","2017-09-08","USA2017"))
[1] 4 4
> # to is non bizdays
> c(bizdays("2017-09-05","2017-09-09","USA2017"),
+   bizdays("2017-09-05","2017-09-08","USA2017"))
[1] 4 4
> 
> bizseq("2017-09-04","2017-09-08","USA2017")
[1] "2017-09-05" "2017-09-06" "2017-09-07" "2017-09-08"
> bizseq("2017-09-04","2017-09-09","USA2017")
[1] "2017-09-05" "2017-09-06" "2017-09-07" "2017-09-08"
> bizseq("2017-09-05","2017-09-08","USA2017")
[1] "2017-09-05" "2017-09-06" "2017-09-07" "2017-09-08"
```

Thanks very much for your feedbacks and contributions.
