### ISSUE TITLE
Clarify adjust.date help documentation

### ISSUE THREAD

**Issue by bbrewington** [wilsonfreitas/R-bizdays#65]
I was a bit confused by the help doc for adjust.date, and the text in your comment on issue #21 was very helpful.  Maybe add that info into the help doc?

Couple questions to clarify:

- What does the "modified" prefix mean?
- Which functions are equivalent (e.g. adjust.next & following)
- Why are there equivalent functions?  (use info from your comment, on how you want to mirror the rolling dates setup)

**Comment by wilsonfreitas** [comment]
Hi @bbrewington, I updated the documentation. I think it is more clear now.
I am closing this issue, but fell free to reopen if you think the docs remain confuse.
Thanks for your help.
