### ISSUE TITLE
TARGET Calendar

### ISSUE THREAD

**Issue by DavideMagno** [wilsonfreitas/R-bizdays#80]
Hi when I look at the range of calendars available from RQuantLib, I can't find the TARGET one, which is the standard for interest rate derivatives in Europa.

Can you please include it in the set?

Thanks,
Davide

**Comment by wilsonfreitas** [comment]
Hi @DavideMagno, thanks for reporting this.
It's done!

**Comment by wilsonfreitas** [comment]
Will be in CRAN soon.
