### ISSUE TITLE
Unexpected outcomes bizdays

### ISSUE THREAD

**Issue by Jaap-R** [wilsonfreitas/R-bizdays#84]
While checking the outcomes from the bizdays function, I saw that there are some unexpected outcomes from this function. For the calculations, I used:

Kalender <- create.calendar(name='MyCalendar',  
                            weekdays=c('saturday', 'sunday'),
                            start.date = ymd("2019-12-28"),
                            end.date = ymd("2021-01-01"))

ts_begin <- seq(as.Date("2020-01-01"), length=13, by="1 month") - days(1)

NrDays <- numeric()
for (i in 1:12) {NrDays[i] =bizdays(ts_begin[i], ts_begin[i+1], Kalender)}
Not accounting for holidays.... These results are expected: Jan: 23 Feb: 20 , March:22, April:22 , May:21 , Jun:22, Jul:23, Aug: 22, Sep:22, Oct:22, Nov:22 and Dec;23

Instead I get (from jan-dec): NrDays [1] 23 20 21 22 21 21 23 21 22 22 20 23

Result unequal to expected: In March (-1), June (-1), Aug(-1), Nov(-2).

Are there suggestions how to solve this, or what my mistakes are?

**Comment by wilsonfreitas** [comment]
Unfortunately this is not straightforward.
If you want the number of business days for each month the best setup is 

```R
create.calendar(name="MyCalendar",
                weekdays=c("saturday", "sunday"),
                start.date = "2019-12-28",
                end.date = "2021-01-01",
                adjust.from = following,
                adjust.to = preceding,
                financial = FALSE)
```

```R
ts_begin <- seq(as.Date("2020-01-01"), length=13, by="1 month")
ts_end <- seq(as.Date("2020-01-01"), length=13, by="1 month") - days(1)

NrDays <- numeric()

ans <- c(23, 20, 22, 22, 21, 22, 23, 21, 22, 22, 21, 23)

for (i in 1:12) {
  NrDays[i] <- bizdays(ts_begin[i], ts_end[i+1], "MyCalendar")
  cat(format(ts_begin[i]), ":", format(ts_end[i+1]), "=", NrDays[i], " ", ans[i], " ", NrDays[i] == ans[i], "\n")
  cat(format(ts_begin[i]), ":", format(ts_end[i+1]), "=", NrDays[i], " ", ans[i], " ", NrDays[i] == ans[i], "\n")
}
```

This leads to

```
2020-01-01 : 2020-01-31 = 23   23   TRUE 
2020-02-01 : 2020-02-29 = 20   20   TRUE 
2020-03-01 : 2020-03-31 = 22   22   TRUE 
2020-04-01 : 2020-04-30 = 22   22   TRUE 
2020-05-01 : 2020-05-31 = 21   21   TRUE 
2020-06-01 : 2020-06-30 = 22   22   TRUE 
2020-07-01 : 2020-07-31 = 23   23   TRUE 
2020-08-01 : 2020-08-31 = 21   21   TRUE 
2020-09-01 : 2020-09-30 = 22   22   TRUE 
2020-10-01 : 2020-10-31 = 22   22   TRUE 
2020-11-01 : 2020-11-30 = 21   21   TRUE 
2020-12-01 : 2020-12-31 = 23   23   TRUE 
```

What is this all about?
When bizdays function is used with nonworking days in its arguments it might lead to unexpected results. As you reported. That's the reason why the arguments `adjust.from` and `adjust.to` have been introduced. These arguments adjust bizdays arguments to the closest business days.

I suggest you to read the [Financial and non financial calendars](https://cran.r-project.org/web/packages/bizdays/vignettes/Financial_and_non_financial.html) vignette.

**Comment by Jaap-R** [comment]
Thanks for your reply!

This is part of creating a cashflow forecast for a consultancy firm. I need
to split the total duration of several project into months. Consultants get
paid per hour/ days worked, thats why I use your function.

Thanks!
Jaap

Op vr 17 apr. 2020 om 13:21 schreef Wilson Freitas <notifications@github.com

**Comment by wilsonfreitas** [comment]
Perfect!
As I said, the setup is no straightforward.
I am closing this issue.
