### ISSUE TITLE
Business Days function not counting the last date

### ISSUE THREAD

**Issue by GitHunter0** [wilsonfreitas/R-bizdays#86]
First, thanks for the package, it is very useful.

The issue is that bizdays() does not seem to be counting the last date, so that it is counting 1 day less than the year actually has. Comparison example:

```
bizdays::load_quantlib_calendars('UnitedStates', from='1996-01-01', to='2040-12-31')
bizdays::bizdays('2020-01-01', '2020-12-31', 'QuantLib/UnitedStates')

RQuantLib::businessDaysBetween(calendar="UnitedStates",
  from=as.Date("2020-01-01"), to=as.Date("2020-12-31"),
  includeFirst = TRUE, includeLast = TRUE)
```
Is there a solution to this?

**Comment by wilsonfreitas** [comment]
Thanks for your contribution,

Please take a look at

<https://cran.r-project.org/web/packages/bizdays/vignettes/Financial_and_non_financial.html>

This is related to financial and non-financial calendars.

If you set `includeLast = FALSE` the desired result appears.

```
RQuantLib::businessDaysBetween(calendar="UnitedStates",
  from=as.Date("2020-01-01"), to=as.Date("2020-12-31"),
  includeFirst = TRUE, includeLast = FALSE)
```

**Comment by GitHunter0** [comment]
Hey @wilsonfreitas , thanks for the feedback, but I guess you misunderstood me. My problem is not with `RQuantLib` but with `bizdays` package whose functions lack the parameter `includeLast`, which I would like to set to TRUE

**Comment by wilsonfreitas** [comment]
Hmmm,

I understand. A `financial` argument can be added to `load_quantlib_calendars` and when set to `FALSE` bizdays would work the way you expect.

```
bizdays::load_quantlib_calendars('UnitedStates', from='1996-01-01', to='2040-12-31', financial=FALSE)
```

**Comment by GitHunter0** [comment]
Thanks, I believe that should be useful

**Comment by wilsonfreitas** [comment]
This is done.
Thanks for your contribution.
