### ISSUE TITLE
Previous business day not working

### ISSUE THREAD

**Issue by tbrown122387** [wilsonfreitas/R-bizdays#89]
I can't get the previous business day. Isn't this supposed to return yesterday?

```
library(bizdays) 
modified.preceding(Sys.Date()) # this is today
modified.preceding(as.Date("2021-05-31")-1) # this is a sunday 
```

From the documentation: "`modified.following` rolls the given date to the next business day, unless it happens in the next month, in this case it re-turns the previous business day. `modified.preceding` is similar to `modified.following`, but rolls the given date to the previous business day.

**Comment by wilsonfreitas** [comment]
Which calendar are you using?

Try `weekends` calendar.

**Comment by tbrown122387** [comment]
I think there are just a lot of words that don't mean what I think they mean. (e.g. previous, weekdays != weekends, etc.) I think I'm looking for something different so I'll roll my own. Thanks anyway.
