### ISSUE TITLE
working days per month not correctly reported by bizDays

### ISSUE THREAD

**Issue by zielaskowski** [wilsonfreitas/R-bizdays#90]
Hello, I have different results from bizday function from what expected. Possibly it's a problem with options. I tried all (almost) combinations, but could not get it right.

Whatever combinations of options i will use there is mismatch at some point. I expect problem is with first and last day of period, but whatever adjust option i use and financial true or false i can't get it right...

This is reproductible example (based on Polish holidays):
task is to count working days in each month

```r
free <- c("2021-01-01", "2021-01-06", "2021-04-04", "2021-04-05", "2021-05-06", "2021-05-03",
            "2021-05-23", "2021-06-03", "2021-08-15", "2021-11-01", "2021-11-11",
            "2021-12-30", "2021-12-26") %>% as.Date
  
  create.calendar(name="pol",
                  holidays = free,
                  weekdays=c("saturday", "sunday"),
                  start.date = as.Date(paste0("1/01/",year),"%d/%m/%Y"),
                  end.date = as.Date(paste0("31/12/",year),"%d/%m/%Y")
                  ) 

cal = calendars()[["pol"]]

db <- tibble(date = ymd(paste0("2021-", 1:12, "-01")),
             bizday = cal$bizdays(from = date, to = date + months(1))) %>% 
      group_by(date) %>% 
      mutate(correct = cal$dates.table %>% as_tibble %>% filter(month==month(date)) %>% .$is_bizday %>% sum)
```

   date       |bizday |correct
------|------|-----
   <date>     | <dbl>   |<dbl>
 2021-01-01    | 19    |  19
  2021-02-01     |20     | 20
  2021-03-01     |23      |23
  2021-04-01     |20      |21
  2021-05-01     |19      |19
  2021-06-01     |21      |21
  2021-07-01     |21    |  22
  2021-08-01     |22      |22
  2021-09-01     |22      |22
 2021-10-01     |20      |21
 2021-11-01     |20      |20
 2021-12-01     |NA      |22

**Comment by wilsonfreitas** [comment]
Take a look at this

https://gist.github.com/wilsonfreitas/666d743ad7621fb28126038b2b964041

**Comment by zielaskowski** [comment]
i see my problem now: i was confused by financial option set to TRUE by default. 
**_...don’t consider the ending business day..._**, means subtracting one day ONLY if this is a BUSINESS day...now looks so clear :)

Setting it to FALSE and adjusting 'to' date by -1 (end of the month instead beginning of next) gives what expected.

Thank you for explanation and great job with the package.
