### ISSUE TITLE
B3 Calendar

### ISSUE THREAD

**Issue by wilsonfreitas** [wilsonfreitas/R-bizdays#96]
In B3 calendar the date

2020-07-09 

is not a holiday.
Due to COVID, some holidays have been antecipated and for this reason B3 works normally in this date.
The holidays list must be changed.

**Comment by rpfreitasxyz** [comment]
Hi, Wilson! I would like to highlight that, via calendars(), none are available. Here's a reprex:

> bizdays::calendars()
> #> Calendars:
> 
> sessionInfo()
> #> R version 4.1.2 (2021-11-01)
> #> Platform: x86_64-w64-mingw32/x64 (64-bit)
> #> Running under: Windows 10 x64 (build 19043)
> #> 
> #> Matrix products: default
> #> 
> #> locale:
> #> [1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
> #> [3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
> #> [5] LC_TIME=Portuguese_Brazil.1252    
> #> 
> #> attached base packages:
> #> [1] stats     graphics  grDevices utils     datasets  methods   base     
> #> 
> #> loaded via a namespace (and not attached):
> #>  [1] rstudioapi_0.13   knitr_1.39        magrittr_2.0.3    bizdays_1.0.9    
> #>  [5] R.cache_0.15.0    rlang_1.0.2       fastmap_1.1.0     fansi_1.0.3      
> #>  [9] stringr_1.4.0     styler_1.7.0      highr_0.9         tools_4.1.2      
> #> [13] xfun_0.30         R.oo_1.24.0       utf8_1.2.2        cli_3.3.0        
> #> [17] withr_2.5.0       htmltools_0.5.2   ellipsis_0.3.2    yaml_2.3.5       
> #> [21] digest_0.6.29     tibble_3.1.6      lifecycle_1.0.1   crayon_1.5.1     
> #> [25] purrr_0.3.4       R.utils_2.11.0    vctrs_0.4.1       fs_1.5.2         
> #> [29] glue_1.6.2        evaluate_0.15     rmarkdown_2.14    reprex_2.0.1     
> #> [33] stringi_1.7.6     compiler_4.1.2    pillar_1.7.0      R.methodsS3_1.8.1
> #> [37] jsonlite_1.8.0    pkgconfig_2.0.3

Is this incidental?

**Comment by wilsonfreitas** [comment]
Hi @rpfreitasxyz, yes, it is.
Now calendars are loaded on package attach and because of that the package must be loaded first (with library or require).

``` r
library(bizdays)
#> 
#> Attaching package: 'bizdays'
#> The following object is masked from 'package:stats':
#> 
#>     offset
calendars()
#> Calendars: 
#> actual, Brazil/ANBIMA, Brazil/B3, weekends
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by wilsonfreitas** [comment]
Done ab3e8f6c09c2550f987fd6dc7862a1da3a9fdb13
